name: Push to Harbor
on:
  push:
    branches:
      - "master"
      - "misp-docker"
    paths:
      - "/**"

jobs:
  build-misp-docker-image:
    name: Build misp image
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Login to Harbor
        uses: docker/login-action@v1
        with:
          registry: c.rzp.io
          username: ${{ secrets.HARBOR_DOCKER_USERNAME }}
          password: ${{ secrets.HARBOR_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: build
        uses: docker/build-push-action@v2
        with:
          file: ./misp-docker/web/Dockerfile
          push: true
          tags: c.rzp.io/razorpay/misp:${{ github.sha }}
